export const VISION_PROMPT = [
  'Return STRICT JSON only. No markdown or code fences.',
  'Output keys: environment, people, social_cues, reliability, notes.',
  'Preferred shape:',
  '{',
  '  "environment": { "label": "...", "confidence": 0.0-1.0, "objects": [], "lighting": { "level": "...", "source": "...", "confidence": 0.0-1.0 }, "noise_or_busyness": { "level": "...", "confidence": 0.0-1.0 } },',
  '  "people": { "count_estimate": 0, "count_confidence": 0.0-1.0, "proximity": "...", "orientation_summary": "...", "confidence": 0.0-1.0 },',
  '  "social_cues": { "facial_expression_summary": { "label": "...", "confidence": 0.0-1.0 }, "body_posture_summary": { "label": "...", "confidence": 0.0-1.0 }, "gaze_summary": { "label": "...", "confidence": 0.0-1.0 }, "interaction_context": { "label": "...", "confidence": 0.0-1.0 } },',
  '  "reliability": { "overall_confidence": 0.0-1.0, "limitations": [] },',
  '  "notes": []',
  '}',
  'Rules:',
  '- Describe the environment only (e.g., study room, classroom, office).',
  '- Do not identify people, demographics, or sensitive attributes.',
  '- social_cues must be probabilistic; use unknown if unsure.',
  '- No medical claims, no diagnosis.',
  '- objects: up to 8 short nouns.',
  '- notes: up to 3 short notes.',
  '- Use confidence fields 0..1 where possible.',
  'Allowed enums:',
  '- lighting.level: low | normal | bright',
  '- lighting.source: natural | indoor | mixed',
  '- noise_or_busyness.level: quiet | moderate | busy',
  '- people.proximity: close | medium | far',
  '- people.orientation_summary: facing_camera | side_profile | back_turned | mixed',
  '- facial_expression_summary.label: neutral | positive | negative | confused | engaged | unknown',
  '- body_posture_summary.label: open | closed | leaning_in | leaning_away | restless | unknown',
  '- gaze_summary.label: toward_camera | away_from_camera | downward | mixed | unknown',
  '- interaction_context.label: conversation | presentation | studying | waiting | unknown'
].join('\n');
